FamilyPerf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('family/', include('fpm.urls')),
]

fpm/urls.py
from django.urls import path
from . import views
app_name ='fpm'

urlpatterns =[
    path('', views.IndexView.as_view(), name='family_index'), # 家庭绩效首页
    path('login/',views.LoginView.as_view(),name='family_login'), #家庭绩效系统登录页
    path('logout/',views.LogoutView.as_view(),name='family_logout'), #家庭绩效系统登录页
    path('perfitems/',views.PerfItemIndexView.as_view(),name='perfitems_index'), #成员绩效项目
    path('perfitems/<int:pk>/', views.PerfItemView.as_view(), name='member_perfitems'),  # 成员绩效项目
    path('perfitems/<int:pk>/add/', views.PerfItemCreateView.as_view(), name='member_perfitems_add'),  # 成员绩效项目
    path('perfitems/<int:pk>/update/', views.PerfItemUpdateView.as_view(), name='member_perfitems_update'),  # 成员绩效项目编辑
    path('perfitems/<int:pk>/delete/', views.PerfItemDeleteView.as_view(), name='member_perfitems_delete'),  # 成员绩效项目删除

    path('perfrecords/',views.PerfRecordIndexView.as_view(), name='perfrecords_index'),
    path('perfrecords/<int:year>-<int:month>-<int:day>/<int:pk>/', views.PerfRecordView.as_view(),name='member_perfrecords'),
    path('perfrecords/<int:year>-<int:month>-<int:day>/<int:pk>/add', views.PerfRecordCreateView.as_view(),
         name='member_perfrecords_add'),

]

templates/base.html
{#templates/base.html#}
{% load staticfiles %}

<!DOCTYPE html>
<!-- saved from url=(0042)https://v3.bootcss.com/examples/dashboard/ -->
<html lang="zh-CN"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
{#    <link rel="icon" href="https://v3.bootcss.com/favicon.ico">#}

    <title>家庭绩效管理</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>

    {% block extra-css %}{% endblock %}

  </head>

  <body>

    {% block body %}

    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

    {% block extra-js %}

    {% endblock %}
</body></html>

templates/index.html
{#templates/index.html#}
{% extends 'base.html' %}

{% block body %}

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">{% block pro_name %}Project name{% endblock %}</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown ">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">{{ request.user }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">个人信息</a></li>
                            <li><a href="{% url 'fpm:family_logout' %}">登出</a></li>
                        </ul>
                    </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
       {% block nav %}
        <li class="active"><a href="{% url 'fpm:family_index' %}">Overview <span class="sr-only">(current)</span></a></li>
        <li><a href="{% url 'fpm:perfitems_index' %}">成员绩效项目</a></li>
         <li><a href="{% url 'fpm:perfrecords_index' %}">成员绩效表</a></li>
        <li><a href="#">Export</a></li>
       {% endblock %}
      </ul>

    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
       {% block right-content-container %}
                <h2 class="page-header">Dashboard</h2>
      {% endblock %}
    </div>
  </div>
</div>

{% endblock %}

templates/login.html
{#templates/login.html#}
{% extends 'index.html' %}
{% load staticfiles %}

{% block extra-css %}
    <link rel="stylesheet" href="{% static 'css/signIn.css' %}">
{% endblock %}

{% block body %}
 <div class="container">
      <form class="form-signin" method="post">
          {% csrf_token %}
        <h2 class="form-signin-heading">家庭绩效管理</h2>
        <label for="username" class="sr-only">用户名</label>
        <input type="text" id="username" name="username" class="form-control" placeholder="用户名" required autofocus>
        <label for="inputPassword" class="sr-only">密码</label>
        <input type="password" id="inputPassword" name="password" class="form-control" placeholder="密码" required>
        <span style="color: red">{{ error_msg }}</span>

        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> 记住我
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
      </form>
 </div> <!-- /container -->
{% endblock %}