FamilyPerf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('family/', include('fpm.urls')),
]

fpm/urls.py
from django.urls import path
from . import views
app_name ='fpm'

urlpatterns =[
    path('', views.IndexView.as_view(), name='family_index'), # 家庭绩效首页
    path('login/',views.LoginView.as_view(),name='family_login'), #家庭绩效系统登录页
    path('logout/',views.LogoutView.as_view(),name='family_logout'), #家庭绩效系统登录页
    path('perfitems/',views.PerfItemIndexView.as_view(),name='perfitems_index'), #成员绩效项目
    path('perfitems/<int:pk>/', views.PerfItemView.as_view(), name='member_perfitems'),  # 成员绩效项目
    path('perfitems/<int:pk>/add/', views.PerfItemCreateView.as_view(), name='member_perfitems_add'),  # 成员绩效项目
    path('perfitems/<int:pk>/update/', views.PerfItemUpdateView.as_view(), name='member_perfitems_update'),  # 成员绩效项目编辑
    path('perfitems/<int:pk>/delete/', views.PerfItemDeleteView.as_view(), name='member_perfitems_delete'),  # 成员绩效项目删除

    path('perfrecords/',views.PerfRecordIndexView.as_view(), name='perfrecords_index'),
    path('perfrecords/<int:year>-<int:month>-<int:day>/<int:pk>/', views.PerfRecordView.as_view(),name='member_perfrecords'),
    path('perfrecords/<int:year>-<int:month>-<int:day>/<int:pk>/add', views.PerfRecordCreateView.as_view(),
         name='member_perfrecords_add'),

]

fpm/models.py
# fpm/model.py
__author__ ='may'
import datetime
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Common(models.Model):
    create_time = models.DateTimeField(verbose_name='创建时间',auto_now_add=True)
    mod_time = models.DateTimeField(verbose_name='修改时间', auto_now=True)

    class Meta:
        abstract = True

class Family(Common):
    #家庭
    name = models.CharField('家庭名', max_length=10, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '家庭表'
        verbose_name_plural = verbose_name

class UserProfile(models.Model):
    '''家庭用户信息表'''
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    family = models.ForeignKey(Family,on_delete=models.CASCADE)

    def __str__(self):
        return '{}的用户{}'.format(self.family.name,self.user.username)

    class Meta:
        verbose_name = '家庭用户表'
        verbose_name_plural = verbose_name

class MemberInfo(Common):
    '''成员表'''
    sex_choices =(
        (0,'男'),
        (1,'女'),
    )
    name = models.CharField('姓名',max_length=64)
    sex = models.SmallIntegerField('性别', choices=sex_choices, default=1)
    age = models.DecimalField('年龄',max_digits=3,decimal_places=0,default=0)
    #score 记录当前的总分
    #一个成员一定属于某个家庭
    family = models.ForeignKey(Family,on_delete=models.CASCADE)

    def __str__(self):
        return '{}的{}'.format(self.family.name,self.name)

    class Meta:
        verbose_name = '成员表'
        verbose_name_plural = verbose_name
        unique_together =['name','family']

class PerfItem(Common):
    '''成员项目表'''
    name = models.CharField('项目名', max_length=256)
    score_up = models.PositiveSmallIntegerField('加分', default=0)
    score_down = models.SmallIntegerField('减分', default=0)
    active = models.BooleanField('状态', default=True)
    member = models.ForeignKey(MemberInfo, verbose_name='成员', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '成员项目表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{}的绩效项目{}'.format(self.member.name,self.name)

class PerfRecord(Common):
    '''绩效记录'''
    day = models.DateField(verbose_name='日期')
    #属于哪个成员
    member = models.ForeignKey(MemberInfo,on_delete=models.CASCADE,verbose_name='成员')
    item = models.ForeignKey(PerfItem, on_delete=models.CASCADE, verbose_name='绩效项')
    score = models.SmallIntegerField(verbose_name='计分')
    description = models.CharField(verbose_name='描述', max_length=256, default='', blank=True)

    class Meta:
        verbose_name = '绩效记录表'
        verbose_name_plural = verbose_name

class Result(Common):
    '''成绩表'''
    day = models.DateField(verbose_name='日期')
    member = models.ForeignKey(MemberInfo,on_delete=models.CASCADE,verbose_name='成员')
    score = models.SmallIntegerField(verbose_name='总分')
    score_sum = models.SmallIntegerField(verbose_name='累计分数')
    description = models.CharField(verbose_name='总评', max_length=256,default='', blank=True)

    def __str__(self):
        return '{}-{}-{}'.format(self.member.name,self.day,self.score)

    class Meta:
        verbose_name = '成绩表'
        verbose_name_plural = verbose_name

fpm/forms.py
from django import forms
from . import models

class PerfRecordForm(forms.Form):
    name = forms.CharField()
    score_up = forms.IntegerField()
    score_down = forms.IntegerField()
    score = forms.IntegerField(required=False)
    description = forms.CharField(required=False)

class PerfItemForm(forms.ModelForm):
    class Meta:
        model = models.PerfItem
        exclude = ['member']

fpm/views.py
import datetime

from django.shortcuts import render, HttpResponse, redirect
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from . import models
from . import forms
from . import utilities

@method_decorator(login_required,name='dispatch')
class PerfItemIndexView(View):
    def get(self,request,*args,**kwargs):
        return render(request,'fpm/perfitems.html')

@method_decorator(login_required,name='dispatch')
class PerfItemView(View):
    def get(self,request, *args, **kwargs):
        member = models.MemberInfo.objects.get(pk=kwargs['pk'])
        perfitems = models.PerfItem.objects.filter(member=member)

        return render(request,'fpm/member_perfitems.html', {'member':member,'perfitems':perfitems})

@method_decorator(login_required,name='dispatch')
class PerfItemCreateView(CreateView):
    model = models.PerfItem
    template_name = 'fpm/member_perfitems.html'
    form_class = forms.PerfItemForm

    def form_valid(self, form):
        member = models.MemberInfo.objects.get(pk=self.kwargs['pk'])
        form.instance.member = member
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['member'] = models.MemberInfo.objects.get(pk=self.kwargs['pk'])
        return context

    def get_success_url(self):
        return reverse_lazy('fpm:member_perfitems', kwargs={'pk': self.kwargs['pk']})

@method_decorator(login_required,name='dispatch')
class PerfItemUpdateView(UpdateView):
    model = models.PerfItem
    template_name = 'fpm/member_perfitems.html'
    form_class = forms.PerfItemForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['member'] = models.PerfItem.objects.get(pk=self.kwargs['pk']).member
        return context

    def get_success_url(self):
        member = models.PerfItem.objects.get(pk=self.kwargs['pk']).member
        return reverse_lazy('fpm:member_perfitems', kwargs={'pk': member.id })

@method_decorator(login_required,name='dispatch')
class PerfItemDeleteView(DeleteView):
    model = models.PerfItem
    template_name = 'fpm/delete_comfirm.html'

    def get_success_url(self):
        member = models.PerfItem.objects.get(pk=self.kwargs['pk']).member
        return reverse_lazy('fpm:member_perfitems', kwargs={'pk': member.id})

@method_decorator(login_required,name='dispatch')
class PerfRecordIndexView(View):
    def get(self,request,*args,**kwargs):
        today = datetime.datetime.now().date()
        days = models.PerfRecord.objects.all().order_by('-day').values_list('day').distinct()
        days = [day[0] for day in list(days)]
        hasToday = today in days
        return render(request,'fpm/member_perfrecordindex.html',{
            'days':days,
            'hasToday': hasToday,
            'today':today
        })

class PerfRecordCreateView(View):
    def post(self,request,*args, **kwargs):
        #根据添加的post,返回json数据
        day = datetime.date(kwargs['year'], kwargs['month'], kwargs['day'])
        member = models.MemberInfo.objects.get(pk=kwargs['pk'])
        perf_item_name = request.POST.get('name') #name and memeber should be unie
        perf_item_scoreup = request.POST.get("score_up",0)
        perf_item_scoredown = request.POST.get("score_down", 0)
        perf_item_active =True if request.POST.get('active')=='on' else False
        record_score = request.POST.get('score')
        record_desc =request.POST.get('desc')
        perfitem = models.PerfItem.objects.filter(member=member,name=perf_item_name)
        if perfitem:
            if perfitem[0].active:
                return JsonResponse({'status':'fail','msg':'已经对有该绩效项'})
            else:
                perfitem = perfitem[0]
        else:
            #创建perfitem
            perfitem = models.PerfItem.objects.create(name=perf_item_name,score_up=int(perf_item_scoreup),
                                                      score_down=int(perf_item_scoredown),
                                                      active=perf_item_active,
                                                      member=member)
        # 创建record
        record = models.PerfRecord.objects.create(day=day, member=member, item=perfitem, score=int(record_score),
                                                  description=record_desc)
        result = models.Result.objects.filter(day=day, member=member)
        if not result:
            result = models.Result.objects.create(day=day, member=member, score=0, score_sum=0)
        else:
            result = result[0]
        result.score += int(record_score)
        result.score_sum += int(record_score)
        result.save()
        return JsonResponse({'status':'ok','item_name':record.item.name,'item_scoreup':record.item.score_up,
                             'item_scoredown':record.item.score_down,'score':record.score,'desc':record.description})
        #return redirect('fpm:member_perfrecords',year=day.year,month=day.month,day=day.day,pk=member.pk)

class PerfRecordView(View):
    def get_sum_result_obj(self,day,member):
        sum_result_obj = {}
        existing_results = models.Result.objects.order_by('-day')
        if not existing_results:
            # 如果没有任何记录，这是集的第一条绩效
            sum_result_obj['pre_sum'] = 0
            sum_result_obj['sum'] = 0
            sum_result_obj['pre_day'] = None
            sum_result_obj['cur_day'] = None
        else:
            day_result = existing_results.filter(day=day, member=member)
            if day_result:
                sum_result_obj['cur_day'] = day_result[0]
                sum_result_obj['sum'] = 0
            else:
                sum_result_obj['cur_day'] = None
                sum_result_obj['sum'] = 0
            pre_results = existing_results.filter(day__lt=day, member=member).order_by('-day')
            if pre_results:
                sum_result_obj['pre_day'] = pre_results[0]
                sum_result_obj['pre_sum'] = pre_results[0].score_sum
            else:
                sum_result_obj['pre_day'] = None
                sum_result_obj['pre_sum'] = 0
        return sum_result_obj
    def post(self,request, *args,**kwargs):
        day = datetime.date(kwargs['year'], kwargs['month'], kwargs['day'])
        member = models.MemberInfo.objects.get(pk=kwargs['pk'])
        keys = set([int(key.split('_')[0]) for key in request.POST.keys() if key != 'csrfmiddlewaretoken' and key !='result_desc'])
        result_desc = request.POST.get('result_desc','')
        sum_result_obj = self.get_sum_result_obj(day,member)
        for k in keys:
            desc = request.POST.get(str(k)+"_desc")
            score = request.POST.get(str(k)+"_score")
            perfitem = models.PerfItem.objects.get(id=k)
            models.PerfRecord.objects.create(day=day,member=member,item=perfitem,score=score,description=desc)
            sum_result_obj['sum'] +=int(score) #累计当前计分
        if sum_result_obj['cur_day']:
            sum_result_obj['cur_day'].score += sum_result_obj['sum']
            sum_result_obj['cur_day'].score_sum += sum_result_obj['sum']
            sum_result_obj['cur_day'].save()
        else:
            #创建新的记录
            score_sum = sum_result_obj['pre_sum'] +  sum_result_obj['sum']
            sum_result_obj['cur_day'] = models.Result.objects.create(day=day,
                                                                     member=member,
                                                                     score=sum_result_obj['sum'],
                                                                     score_sum=score_sum,
                                                                     description=result_desc)

        return redirect('fpm:member_perfrecords',year=day.year,month=day.month,day=day.day,pk=member.pk)
    def get(self,request, *args, **kwargs):
        today = datetime.datetime.now().date()
        day = datetime.date(kwargs['year'],kwargs['month'],kwargs['day'])
        member = models.MemberInfo.objects.get(pk=kwargs['pk'])
        records = models.PerfRecord.objects.filter(day=day,member=member)
        sum_result_obj = utilities.dict_to_object(self.get_sum_result_obj(day,member))
        if not records and today == day:
            #今天的没有记录 该显示 输入表
            items = models.PerfItem.objects.filter(member=member,active=True)
            return render(request, 'fpm/member_perfrecords_input.html',
                          {'member': member,
                           'day': day,
                           'items':items,
                           'sum_result_obj':sum_result_obj})
        elif records:
           # return render(request,'fpm/member_perfrecords.html')
           return render(request, 'fpm/member_perfrecords.html',
                         {'member': member,
                          'day': day,
                          'records':records,
                          'sum_result_obj':sum_result_obj})
        else:
            #return HttpResponse("not today and no record")
            return render(request, 'fpm/member_perfrecords.html',
                          {'member': member,
                           'day': day,
                           'sum_result_obj':sum_result_obj})
        return render(request, 'fpm/member_perfrecords.html',
                      {'member':member,
                       'day':day,
                       'sum_result_obj':sum_result_obj})

@method_decorator(login_required,name='dispatch')
class IndexView(View):
    def get(self,request,*args,**kwargs):
        return render(request,'fpm/dashboard.html')

class LoginView(View):

templates/fpm/dashboard.html
{#templates/crm/dashboard.html#}

{% extends 'index.html' %}

{% block pro_name %}{{ request.user.userprofile.family.name }}绩效管理{% endblock %}

templates/fpm/delete_comfirm.html
{% extends 'fpm/dashboard.html' %}

{% block extra-css %}
    <style>
        .hide{
            display:none;
        }

    </style>
{% endblock %}

{% block nav %}
        <li ><a href="#">Overview</a></li>
        <li class="active"><a href="{% url 'fpm:perfitems_index' %}">成员绩效项目 <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Analytics</a></li>
        <li><a href="#">Export</a></li>
{% endblock %}
 {% block right-content-container %}
    <h2 class="page-header">{{ member.name }}绩效项目页面</h2>
   <form method="post">
       {% csrf_token %}
    <p>你确定要删除 {{perfitem}}?</p>
    <input type="submit" value="确定">
</form>
 {% endblock %}

templates/fpm/member_perfitems.html
{% extends 'fpm/perfitems.html' %}

{% block extra-css %}
    <style>
        .hide{
            display:none;
        }

    </style>
{% endblock %}

 {% block right-content-container %}
    <h2 class="page-header">{{ member.name }}绩效项目页面</h2>
    <div>
        <a href="#" class="btn btn-info" id="perfitem-btnadd">添加</a>
        <div id="perfitem-form" class="hide" >
            <form class="form-inline" method="post" action="{% url 'fpm:member_perfitems_add' member.id %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name">项目名</label>
                    <input type="text" class="form-control" id="id_name" name="name" >
                </div>
                <div class="form-group">
                    <label for="id_score_up">得分</label>
                    <input type="number" min="0" class="form-control" id="id_score_up" name="score_up" >
                </div>
                <div class="form-group">
                    <label for="id_score_down">减分</label>
                    <input type="number" class="form-control" max="0" id="id_score_down" name="score_down" >
                </div>
                <div class="form-group">
                   <label for="id_active">状态</label>
                   <input type="checkbox" name="active" id="id_active" checked="">
                </div>
                 <button type="submit" class="btn btn-default" id="perfitem-savebtn">保存</button>
            </form>
        </div>
        <table class="table table-striped " id="perfitem-table">
            <thead>
                <tr>
                    <th>项目名</th>
                    <th>做了得分</th>
                    <th>不做减分</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {% for item in perfitems  %}
                    <tr>
                        <td>{{item.name}}</td>
                        <td>{{item.score_up}}</td>
                        <td>{{item.score_down}}</td>
                        <td>{% if item.active %}活动{% else %}停用 {% endif %}</td>
                        <td data-id="{{item.id}}" >
                            <a  href="#" class="edit btn btn-default">编辑</a>
                            <a href="{% url 'fpm:member_perfitems_delete' item.id %}"  class="del btn btn-danger">删除</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
 {% endblock %}

 {% block extra-js %}
    <script>
        var csrftoken = $.cookie('csrftoken');
        function csrfSafeMethod(method){
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        function perfitem_change (){
            var that = event.currentTarget;
            var tr_element = $(that).parent().parent();
            var id = $(that).parent().data("id");
            var form_data ={
                'name':tr_element.find('input[name="edit_name"]').first().val(),
                'score_up':tr_element.find('input[name="edit_score_up"]').first().val(),
                'score_down':tr_element.find('input[name="edit_score_down"]').first().val(),
                'active':tr_element.find('input[name="edit_active"]').is(':checked')
            };
            console.log(form_data);
            $.ajax({
                url: '/family/perfitems/'+ id +'/update/',
                data:form_data,
                type: 'POST',
                dataType: 'json',
                beforeSend: function(xhr,settings){
                    if(!csrfSafeMethod(settings.type) && !this.crossDomain){
                        xhr.setRequestHeader("X-CSRFToken",csrftoken);
                    }},
                complete: function(xhr,status){
                    window.location.reload();
                },
            });//ajax
        }

        $(document).ready(function(){
            $('#perfitem-btnadd').on('click', function(e){
                e.preventDefault();
                $("#perfitem-form").toggleClass("hide");
            }); // # add perfitem action
        });
        $(".edit").on('click', function(e){
           var $action_td = $(e.target).parent();
           var $tds = $($action_td).siblings();
           //换成 编辑模式
           var  $td_name_element ='<input type="text" class="form-control" id="id_edit_name" name="edit_name" ' + 'value="' + $($tds[0]).text() + '" >';
           var $td_scoreup_element =' <input type="number" min="0" class="form-control" id="id_edit_score_up" name="edit_score_up" ' + 'value="' + $($tds[1]).text() + '" >';
           var $td_scoredown_element ='<input type="number" class="form-control" max="0" id="id_edit_score_down" name="edit_score_down"  ' + 'value="' + $($tds[2]).text() + '" >';
           if($($tds[3]).text()=="活动"){
                var $td_active_element ='<input type="checkbox" name="edit_active" id="id_edit_active" checked="">';
            }else {
               var $td_active_element ='<input type="checkbox" name="edit_active" id="id_edit_active">';
            }

            $($tds[0]).html($td_name_element);
            $($tds[1]).html($td_scoreup_element);
            $($tds[2]).html($td_scoredown_element);
            $($tds[3]).html($td_active_element);
            $($action_td).html('<button type="button" class="btn btn-default perfitem-change" onclick="perfitem_change()">保存</button>')
            //发送编辑请求
        });// edit perfitem
    </script>
 {% endblock %}

templates/fpm/member_perfrecordindex.html
{% extends 'fpm/dashboard.html' %}

{% block nav %}
        <li ><a href="{% url 'fpm:family_index' %}">Overview</a></li>
        <li><a href="{% url 'fpm:perfitems_index' %}">成员绩效项目</a></li>
        <li  class="active"><a href="{% url 'fpm:perfrecords_index' %}">成员绩效表<span class="sr-only">(current)</span></a></li>
        <li><a href="#">Export</a></li>
{% endblock %}
 {% block right-content-container %}
    <h2 class="page-header">{{ request.user.userprofile.family.name}}成员积分单索引页面</h2>
     <table class="table table-striped ">
            <thead>
                <tr>
                    <th>日期</th>
                     {% for member in request.user.userprofile.family.memberinfo_set.all  %}
                    <th>{{ member.name }}</th>
                     {% endfor %}
                </tr>
            </thead>
            <tbody>
            {% if not hasToday %}
                <tr>
                    <td>{{ today |date:'Y-m-j' }}</td>
                    {% for member in request.user.userprofile.family.memberinfo_set.all  %}
                    <td><a href="{% url 'fpm:member_perfrecords' today.year today.month today.day member.id %}">查看</a></td>
                    {% endfor %}
                </tr>
            {% endif %}
                {% for day in days %}
                    <tr>
                        <td>{{ day |date:"Y-m-j"}}</td>
                        {% for member in request.user.userprofile.family.memberinfo_set.all  %}
                        <td><a href="{% url 'fpm:member_perfrecords' day.year day.month day.day member.id %}">查看</a></td>
                    {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
 {% endblock %}

 {% block extra-js %}

 {% endblock %}

templates/fpm/member_perfrecords_input.html
{% extends 'fpm/member_perfrecordindex.html' %}
{% block extra-css %}
    <style>
        .hide{
            display:none;
        }

    </style>
{% endblock %}
{% block right-content-container %}
     <h2 class="page-header">{{ member.name }} {{day|date:"Y-m-d"}} 积分情况</h2>
    <div>
        <table class="table table-bordered">
        <caption>积分结果信息</caption>
        <thead>
            <tr>
                <th>最近积分日期</th>
                <th>最近积分</th>
                <th>今日得分</th>
                <th>今日累积得分</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    {% if sum_result_obj.pre_day %}
                    <a href="{% url 'fpm:member_perfrecords' sum_result_obj.pre_day.day.year sum_result_obj.pre_day.day.month sum_result_obj.pre_day.day.day  member.id %}">
                    {{sum_result_obj.pre_day.day |date:"Y-m-j"}}
                    </a>
                    {% else %} 没有上条记录 {% endif %}
                </td>
                <td>{{sum_result_obj.pre_sum}}</td>
                <td>{% if sum_result_obj.cur_day %}{{sum_result_obj.cur_day.score }}{% else %} 0 {% endif %} </td>
                <td>{% if sum_result_obj.cur_day %}{{sum_result_obj.cur_day.score_sum }}{% else %} 0 {% endif %} </td>
            </tr>
        </tbody>
    </table>
        <button class="btn btn-info" id="btn-record-add">添加临时项</button>
        <div id="record-form" class="hide" >
             <form class="form-inline" method="post">
                 <div class="form-group">
                    <label for="id_name">项目名</label>
                    <input type="text" class="form-control" id="id_name" name="name" required >
                </div>
                 <div class="form-group">
                    <label for="id_score_up">加分</label>
                    <input type="number" min="0" class="form-control" id="id_score_up" name="score_up" required >
                </div>
                <div class="form-group">
                    <label for="id_score_down">减分</label>
                    <input type="number" class="form-control" max="0" id="id_score_down" name="score_down" required >
                </div>
                <div class="form-group">
                   <label for="id_active">永久</label>
                   <input type="checkbox" name="active" id="id_active" checked="">
                </div>
                 <div class="form-group">
                    <label for="id_score">本次得分</label>
                    <input type="text" class="form-control" id="id_score" name="score" required >
                </div>
                 <div class="form-group">
                    <label for="id_desc">备注</label>
                    <input type="text" class="form-control" id="id_desc" name="desc" >
                </div>
                 <button type="submit" class="btn btn-warning" id="record-savebtn">添加</button>
             </form>
        </div>
        <table class="table table-striped " id="record_table">
            <thead>
                <tr>
                    <th>项目名</th>
                    <th>做了加分</th>
                    <th>不做减分</th>
                    <th>得分</th>
                    <th>描述</th>
                </tr>
            </thead>
            <tbody>
                <form method="post" action="{% url 'fpm:member_perfrecords' day.year day.month day.day member.id %}">
                    {% csrf_token %}
                   <button type="submit" class="btn btn-primary">保存</button>
                    <tr>
                        <td colspan="5"><input type="text" name="result_desc" placeholder="请输入总评价"></td>
                    </tr>
                {% for item in items %}
                    <tr>
                        <td>{{ item.name }}</td>
                        <td>
                            <input type="radio"  name="{{item.id}}_score" value="{{ item.score_up }}" checked  > {{ item.score_up }}
                        </td>
                        <td>
                            <input type="radio"  name="{{item.id}}_score" value="{{ item.score_down }}"> {{ item.score_down }}
                        </td>
                        <td>0</td>
                        <td><input type="text"  name="{{item.id}}_desc" placeholder="如果有备注,填这里"></td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="5">{{member.name }}没有任何活动的绩效项，请先<a href="{% url 'fpm:member_perfitems_add' member.id %}">添加绩效</a> </td>
                    </tr>
                {% endfor %}
                </form>
            </tbody>
     </table>
    </div>
{% endblock %}

{% block extra-js %}
    <script>
        var csrftoken = $.cookie('csrftoken');
        function csrfSafeMethod(method){
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        String.format = function() {
    if( arguments.length == 0 )
        return null;

    var str = arguments[0];
    for(var i=1;i<arguments.length;i++) {
        var re = new RegExp('\\{' + (i-1) + '\\}','gm');
        str = str.replace(re, arguments[i]);
    }
    return str;
}

        $(document).ready(function(){
            $('#btn-record-add').on('click',function(e){
                e.preventDefault();
                $("#record-form").toggleClass("hide");
            }); // show record add

            $('#record-savebtn').on('click',function(e){
                 e.preventDefault();
                 form = $(this).parents('form');
                 score_up = form.find("input[name='score_up']").val();
                 score_down=form.find("input[name='score_down']").val();
                 score =form.find("input[name='score']").val();
                 if(score != score_up && score != score_down){
                    alert("本次得分的值必须和加分或减分一致!");
                 }
                  $.ajax({
                url: "{% url 'fpm:member_perfrecords_add' day.year day.month day.day member.id %}",
                data:form.serialize(),
                type: 'POST',
                dataType: 'json',
                beforeSend: function(xhr,settings){
                    if(!csrfSafeMethod(settings.type) && !this.crossDomain){
                        xhr.setRequestHeader("X-CSRFToken",csrftoken);
                    }},
                success: function(data){
                    if(data['status'] =='fail'){
                        alert(data['msg']);
                    }else if(data['status'] =='ok'){
                        var record_ele = "<tr><td>{0}</td><td>{1}</td><td>{2}</td><td>{3}</td><td>{4}</td>";
                        record_ele = String.format(record_ele,data['item_name'],
                        data['item_scoreup'],data['item_scoredown'],data['score'],data['desc']);
                         console.log(record_ele)
                        $('#record_table tbody').append(record_ele);
                         $("#record-form").toggleClass("hide");
                    }
                },
            });//ajax
            });// submit
            });//ready
    </script>
 {% endblock %}

templates/fpm/perfItems.html
{#templates/crm/dashboard.html#}

{% extends 'fpm/dashboard.html' %}

{% block nav %}
        <li ><a href="{% url 'fpm:family_index' %}">Overview</a></li>
        <li class="active"><a href="{% url 'fpm:perfitems_index' %}">成员绩效项目 <span class="sr-only">(current)</span></a></li>
        <li><a href="{% url 'fpm:perfrecords_index' %}">成员绩效表</a></li>
        <li><a href="#">Export</a></li>
       {% endblock %}

 {% block right-content-container %}
        <h2 class="page-header">{{ request.user.userprofile.family.name }}成员绩效项目页面</h2>
    <div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>成员名</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {% for member in request.user.userprofile.family.memberinfo_set.all  %}
                    <tr>
                        <td><a href="{% url 'fpm:member_perfitems' member.id %}">{{ member.name }}</a></td>
                        <td>添加</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
 {% endblock %}